str = input()
str = str.replace("c=", "a")
str = str.replace("dz=", "a")
str = str.replace("c-", "a")
str = str.replace("d-", "a")
str = str.replace("lj", "a")
str = str.replace("nj", "a")
str = str.replace("s=", "a")
str = str.replace("z=", "a")
print(len(str))